export type TekduzenCodeRow = {
  code: string;
  title: string;
  classCode: string;
};

// Generated from tekduzhesapplani.pdf in repo root.
export const tekduzenCodeRows: TekduzenCodeRow[] = [
  { code: '100', title: 'Kasa', classCode: '1' },
  { code: '101', title: 'Alınan Çekler', classCode: '1' },
  { code: '102', title: 'Bankalar', classCode: '1' },
  { code: '103', title: 'Verilen Çek. ve Öde. Emirleri (-)', classCode: '1' },
  { code: '108', title: 'Diğer Hazır Değerler', classCode: '1' },
  { code: '110', title: 'Hisse Senetleri', classCode: '1' },
  { code: '111', title: 'Özel Kesim Tahvil ,Senet ve Bonoları', classCode: '1' },
  { code: '112', title: 'Kamu Kesimi Tahvil , Senet ve Bonoları', classCode: '1' },
  { code: '118', title: 'Diğer Menkul Kıymetler', classCode: '1' },
  { code: '119', title: 'Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)', classCode: '1' },
  { code: '120', title: 'Alıcılar', classCode: '1' },
  { code: '121', title: 'Alacak Senetleri', classCode: '1' },
  { code: '122', title: 'Alacak Senetleri Reeskontu (-)', classCode: '1' },
  { code: '124', title: 'Kazanılmamış Finansal Kiralama Faiz Gelirleri(-)', classCode: '1' },
  { code: '126', title: 'Verilen Depozito ve Teminatlar', classCode: '1' },
  { code: '127', title: 'Diğer Ticari Alacaklar Senet ve Bonoları', classCode: '1' },
  { code: '128', title: 'Şüpheli Ticari Alacaklar', classCode: '1' },
  { code: '129', title: 'Şüpheli Ticari Alacaklar Karşılığı (-)', classCode: '1' },
  { code: '131', title: 'Ortaklardan Alacaklar', classCode: '1' },
  { code: '132', title: 'İştiraklerden Alacaklar', classCode: '1' },
  { code: '133', title: 'Bağlı Ortaklıklardan Alacaklar', classCode: '1' },
  { code: '135', title: 'Personelden Alacaklar', classCode: '1' },
  { code: '136', title: 'Diğer Çeşitli Alacaklar', classCode: '1' },
  { code: '137', title: 'Diğer Alacak Senetleri Reeskontu (-)', classCode: '1' },
  { code: '138', title: 'Şüpheli Diğer Alacaklar', classCode: '1' },
  { code: '139', title: 'Şüpheli Diğer Alacaklar Karş. (-)', classCode: '1' },
  { code: '150', title: 'İlk Madde ve Malzeme', classCode: '1' },
  { code: '151', title: 'Yarı Mamuller - Üretim', classCode: '1' },
  { code: '152', title: 'Mamuller', classCode: '1' },
  { code: '153', title: 'Ticari Mallar', classCode: '1' },
  { code: '157', title: 'Diğer Stoklar', classCode: '1' },
  { code: '158', title: 'Stok Değer Düşüklüğü Karşı (-)', classCode: '1' },
  { code: '159', title: 'Verilen Sipariş Avansları', classCode: '1' },
  { code: '178', title: 'Yıllara Yaygın İnşaat Enflasyon Düzeltme', classCode: '1' },
  { code: '179', title: 'Taşeronlara Verilen Avanslar', classCode: '1' },
  { code: '180', title: 'Gelecek Aylara Ait Giderler', classCode: '1' },
  { code: '181', title: 'Gelir Tahakkukları', classCode: '1' },
  { code: '190', title: 'Devreden KDV', classCode: '1' },
  { code: '191', title: 'İndirilecek KDV', classCode: '1' },
  { code: '192', title: 'Diğer KDV', classCode: '1' },
  { code: '193', title: 'Peşin Ödenen Vergiler ve Fonlar', classCode: '1' },
  { code: '195', title: 'İş Avansları', classCode: '1' },
  { code: '196', title: 'Personel Avansları', classCode: '1' },
  { code: '197', title: 'Sayım ve Tesellüm Noksanlar', classCode: '1' },
  { code: '198', title: 'Diğer Çeşitli Dönen Varlıklar', classCode: '1' },
  { code: '199', title: 'Diğer Dönen Varlık. Karşılığı (-)', classCode: '1' },
  { code: '220', title: 'Alıcılar', classCode: '2' },
  { code: '221', title: 'Alacak Senetleri', classCode: '2' },
  { code: '222', title: 'Alacak Senetleri Reeskontu (-)', classCode: '2' },
  { code: '224', title: 'Kazanılmamış Finansal Kiralama Faiz Gelirleri(-)', classCode: '2' },
  { code: '226', title: 'Verilen Depozito ve Teminatlar', classCode: '2' },
  { code: '229', title: 'Şüpheli Alacaklar Karşılığı (-)', classCode: '2' },
  { code: '231', title: 'Ortaklardan Alacaklar', classCode: '2' },
  { code: '232', title: 'İştiraklerden Alacaklar', classCode: '2' },
  { code: '233', title: 'Bağlı Ortaklıklardan Alacaklar', classCode: '2' },
  { code: '235', title: 'Personelden Alacaklar', classCode: '2' },
  { code: '236', title: 'Diğer Çeşitli Alacaklar', classCode: '2' },
  { code: '237', title: 'Diğer Alacak Senet. Reeskontu (-)', classCode: '2' },
  { code: '238', title: 'DİĞER ALACAK SENETLERİ REESKONTU (-)', classCode: '2' },
  { code: '239', title: 'Şüpheli Diğer Alacaklar Karşılığı (-)', classCode: '2' },
  { code: '240', title: 'Bağlı Menkul Kıymetler', classCode: '2' },
  { code: '241', title: 'Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)', classCode: '2' },
  { code: '242', title: 'İştirakler', classCode: '2' },
  { code: '243', title: 'İştiraklere Sermaye Taahhütleri (-)', classCode: '2' },
  { code: '244', title: 'İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)', classCode: '2' },
  { code: '245', title: 'Bağlı Ortaklıklar', classCode: '2' },
  { code: '246', title: 'Bağlı Ortaklıklara Sermaye Taahhütleri (-)', classCode: '2' },
  { code: '247', title: 'Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)', classCode: '2' },
  { code: '248', title: 'Diğer Mali Duran Varlıklar', classCode: '2' },
  { code: '249', title: 'Diğer Mali Duran Varlıklar Karşılığı (-)', classCode: '2' },
  { code: '250', title: 'Arazi ve Arsalar', classCode: '2' },
  { code: '251', title: 'Yeraltı ve Yerüstü Düzenleri', classCode: '2' },
  { code: '252', title: 'Binalar', classCode: '2' },
  { code: '253', title: 'Tesis, Makine ve Cihazlar', classCode: '2' },
  { code: '254', title: 'Taşıtlar', classCode: '2' },
  { code: '255', title: 'Demirbaşlar', classCode: '2' },
  { code: '256', title: 'Diğer Maddi Duran Varlıklar', classCode: '2' },
  { code: '257', title: 'Birikmiş Amortismanlar (-)', classCode: '2' },
  { code: '258', title: 'Yapılmakta Olan Yatırımlar', classCode: '2' },
  { code: '259', title: 'Verilen Avanslar', classCode: '2' },
  { code: '260', title: 'Haklar', classCode: '2' },
  { code: '261', title: 'Şerefiye', classCode: '2' },
  { code: '262', title: 'Kuruluş ve Örgütlenme Giderleri', classCode: '2' },
  { code: '263', title: 'Araştırma ve Geliştirme Giderleri', classCode: '2' },
  { code: '264', title: 'Özel Maliyetler', classCode: '2' },
  { code: '267', title: 'Diğer Maddi Olmayan Duran Varlıklar', classCode: '2' },
  { code: '268', title: 'Birikmiş Amortismanlar (-)', classCode: '2' },
  { code: '269', title: 'Verilen Avanslar', classCode: '2' },
  { code: '271', title: 'Arama Giderleri', classCode: '2' },
  { code: '272', title: 'Hazırlık ve Geliştirme Giderleri', classCode: '2' },
  { code: '277', title: 'Diğer Özel Tükenmeye Tabi Varlıklar', classCode: '2' },
  { code: '278', title: 'Birikmiş Tükenme Payları (-)', classCode: '2' },
  { code: '279', title: 'Verilen Avanslar', classCode: '2' },
  { code: '280', title: 'Gelecek Yıllara Ait Giderler', classCode: '2' },
  { code: '281', title: 'Gelir Tahakkukları', classCode: '2' },
  { code: '291', title: 'Gelecek Yıllarda İndirilecek KDV', classCode: '2' },
  { code: '292', title: 'Diğer KDV', classCode: '2' },
  { code: '293', title: 'Gelecek Yıllar İhtiyacı Stoklar', classCode: '2' },
  { code: '294', title: 'Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar', classCode: '2' },
  { code: '295', title: 'Peşin Ödenen Vergiler ve Fonlar', classCode: '2' },
  { code: '297', title: 'Diğer Çeşitli Duran Varlıklar', classCode: '2' },
  { code: '298', title: 'Stok Değer Düşüklüğü Karşı. (-)', classCode: '2' },
  { code: '299', title: 'Birikmiş Amortismanlar (-)', classCode: '2' },
  { code: '300', title: 'Banka Kredileri', classCode: '3' },
  { code: '301', title: 'Finansal Kiralama İşlemlerinden Borçlar', classCode: '3' },
  { code: '302', title: 'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri(-)', classCode: '3' },
  { code: '303', title: 'Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri', classCode: '3' },
  { code: '304', title: 'Tahvil Anapara Borç ,Taksit ve Faizleri', classCode: '3' },
  { code: '305', title: 'Çıkarılmış Bonolar ve Senetler', classCode: '3' },
  { code: '306', title: 'Çıkarılmış Diğer Menkul Kıymetler', classCode: '3' },
  { code: '308', title: 'Menkul Kıymetler İhraç Farkları (-)', classCode: '3' },
  { code: '309', title: 'Diğer Mali Borçlar', classCode: '3' },
  { code: '320', title: 'Satıcılar', classCode: '3' },
  { code: '321', title: 'Borç Senetleri', classCode: '3' },
  { code: '322', title: 'Borç Senetleri Reeskontu (-)', classCode: '3' },
  { code: '326', title: 'Alınan Depozito ve Teminatlar', classCode: '3' },
  { code: '329', title: 'Diğer Ticari Borçlar', classCode: '3' },
  { code: '331', title: 'Ortaklara Borçlar', classCode: '3' },
  { code: '332', title: 'İştiraklere Borçlar', classCode: '3' },
  { code: '333', title: 'Bağlı Ortaklıklara Borçlar', classCode: '3' },
  { code: '335', title: 'Personele Borçlar', classCode: '3' },
  { code: '336', title: 'Diğer Çeşitli Borçlar', classCode: '3' },
  { code: '337', title: 'Diğer Borç Senetleri Reeskontu (-)', classCode: '3' },
  { code: '340', title: 'Alınan Sipariş Avansları', classCode: '3' },
  { code: '349', title: 'Alınan Diğer Avanslar', classCode: '3' },
  { code: '350', title: 'Yıllara Yaygın İnşaat ve Onarım Hakedişleri', classCode: '3' },
  { code: '358', title: 'Yıllara Yaygın İnşaat Enflasyon Düzeltme', classCode: '3' },
  { code: '360', title: 'Ödenecek Vergi ve Fonlar', classCode: '3' },
  { code: '361', title: 'Ödenecek Sosyal Güvenlik Kesintileri', classCode: '3' },
  { code: '368', title: 'Vadesi Geçmiş, Erte. veya Taksi. Vergi ve Diğ. Yüküm.', classCode: '3' },
  { code: '369', title: 'Ödenecek Diğer Yükümlülükler', classCode: '3' },
  { code: '370', title: 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', classCode: '3' },
  { code: '371', title: 'Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', classCode: '3' },
  { code: '372', title: 'Kıdem Tazminatı Karşılığı', classCode: '3' },
  { code: '373', title: 'Maliyet Giderleri Karşılığı', classCode: '3' },
  { code: '379', title: 'Diğer Borç ve Gider Karşılıkları', classCode: '3' },
  { code: '380', title: 'Gelecek Aylara Ait Gelirler', classCode: '3' },
  { code: '381', title: 'Gider Tahakkukları', classCode: '3' },
  { code: '391', title: 'Hesaplanan KDV', classCode: '3' },
  { code: '392', title: 'Diğer KDV', classCode: '3' },
  { code: '393', title: 'Merkez ve Şubeler Cari Hesabı', classCode: '3' },
  { code: '397', title: 'Sayım ve Tesellüm Fazlaları', classCode: '3' },
  { code: '399', title: 'Diğer Çeşitli Yabancı Kaynaklar', classCode: '3' },
  { code: '400', title: 'Banka Kredileri', classCode: '4' },
  { code: '401', title: 'Finansal Kiralama İşlemlerinden Borçlar', classCode: '4' },
  { code: '402', title: 'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri(-)', classCode: '4' },
  { code: '405', title: 'Çıkarılmış Tahviller', classCode: '4' },
  { code: '407', title: 'Çıkarılmış Diğer Menkul Kıymetler', classCode: '4' },
  { code: '408', title: 'Menkul Kıymetler İhraç Farkı (-)', classCode: '4' },
  { code: '409', title: 'Diğer Mali Borçlar', classCode: '4' },
  { code: '420', title: 'Satıcılar', classCode: '4' },
  { code: '421', title: 'Borç Senetleri', classCode: '4' },
  { code: '422', title: 'Borç Senetleri Reeskontu (-)', classCode: '4' },
  { code: '426', title: 'Alınan Depozito ve Teminatlar', classCode: '4' },
  { code: '429', title: 'Diğer Ticari Borçlar', classCode: '4' },
  { code: '431', title: 'Ortaklara Borçlar', classCode: '4' },
  { code: '432', title: 'İştiraklere Borçlar', classCode: '4' },
  { code: '433', title: 'Bağlı Ortaklıklara Borçlar', classCode: '4' },
  { code: '436', title: 'Diğer Çeşitli Borçlar', classCode: '4' },
  { code: '437', title: 'Diğer Borçlar Senetleri Reeskontu. (-)', classCode: '4' },
  { code: '438', title: 'Kamuya Olan Ertelenmiş veya Taksitlendirilmiş Borçlar', classCode: '4' },
  { code: '439', title: 'DİĞER ÇEŞİTLİ BORÇLAR', classCode: '4' },
  { code: '440', title: 'Alınan Sipariş Avansları', classCode: '4' },
  { code: '449', title: 'Alınan Diğer Avanslar', classCode: '4' },
  { code: '472', title: 'Kıdem Tazminatı Karşılığı', classCode: '4' },
  { code: '479', title: 'Diğer Borç ve Gider Karşılıkları', classCode: '4' },
  { code: '480', title: 'Gelecek Yıllara Ait Gelirler', classCode: '4' },
  { code: '481', title: 'Gider Tahakkukları', classCode: '4' },
  { code: '492', title: 'Gelecek Yıllara Ertelenen veya Terkin Edilecek Katma Değer Vergisi', classCode: '4' },
  { code: '493', title: 'Tesise Katılma Payları', classCode: '4' },
  { code: '499', title: 'Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar', classCode: '4' },
  { code: '500', title: 'Sermaye', classCode: '5' },
  { code: '501', title: 'Ödenmemiş Sermaye (-)', classCode: '5' },
  { code: '502', title: 'Sermaye Düzeltmesi Olumlu Farkları', classCode: '5' },
  { code: '503', title: 'Sermaye Düzeltmesi Olumsuz Farkları (-)', classCode: '5' },
  { code: '520', title: 'Hisse Senedi İhraç Primleri', classCode: '5' },
  { code: '521', title: 'Hisse Senedi İptal Karları', classCode: '5' },
  { code: '522', title: 'MDV Yeniden Değerleme Artışları', classCode: '5' },
  { code: '523', title: 'İştirakler Yeniden Değerleme Artışları', classCode: '5' },
  { code: '524', title: 'Maliyet Artışları Fonu', classCode: '5' },
  { code: '529', title: 'Diğer Sermaye Yedekleri', classCode: '5' },
  { code: '540', title: 'Yasal Yedekler', classCode: '5' },
  { code: '541', title: 'Statü Yedekleri', classCode: '5' },
  { code: '542', title: 'Olağanüstü Yedekler', classCode: '5' },
  { code: '548', title: 'Diğer Kar Yedekleri', classCode: '5' },
  { code: '549', title: 'Özel Fonlar', classCode: '5' },
  { code: '570', title: 'Geçmiş Yıllar Karları', classCode: '5' },
  { code: '580', title: 'Geçmiş Yıllar Zararları (-)', classCode: '5' },
  { code: '590', title: 'Dönem Net Karı', classCode: '5' },
  { code: '591', title: 'Dönem Net Zararı (-)', classCode: '5' },
  { code: '600', title: 'Yurtiçi Satışlar', classCode: '6' },
  { code: '601', title: 'Yurtdışı Satışlar', classCode: '6' },
  { code: '602', title: 'Diğer Gelirler', classCode: '6' },
  { code: '610', title: 'Satıştan İadeler (-)', classCode: '6' },
  { code: '611', title: 'Satış İskontoları (-)', classCode: '6' },
  { code: '612', title: 'Diğer İndirimler (-)', classCode: '6' },
  { code: '620', title: 'Satılan Mamuller Maliyeti (-)', classCode: '6' },
  { code: '621', title: 'Satılan Ticari Mallar Maliyeti (-)', classCode: '6' },
  { code: '622', title: 'Satılan Hizmet Maliyeti (-)', classCode: '6' },
  { code: '623', title: 'Diğer Satışların Maliyeti (-)', classCode: '6' },
  { code: '630', title: 'Araştırma ve Geliştirme Gider (-)', classCode: '6' },
  { code: '631', title: 'Pazarlama ,Satış ve Dağıtım Gider (-)', classCode: '6' },
  { code: '632', title: 'Genel Yönetim Giderleri(-)', classCode: '6' },
  { code: '640', title: 'İştiraklerden Temettü Gelirleri', classCode: '6' },
  { code: '641', title: 'Bağlı Ortaklıklardan Temettü Gelirleri', classCode: '6' },
  { code: '642', title: 'Faiz Gelirleri', classCode: '6' },
  { code: '643', title: 'Komisyon Gelirleri', classCode: '6' },
  { code: '644', title: 'Konusu Kalmayan Karşılıklar', classCode: '6' },
  { code: '645', title: 'Menkul Kıymet Satış Karları', classCode: '6' },
  { code: '646', title: 'Kambiyo Karları', classCode: '6' },
  { code: '647', title: 'Reeskont Faiz Gelirleri', classCode: '6' },
  { code: '648', title: 'Enflasyon Düzeltmesi Karları', classCode: '6' },
  { code: '649', title: 'Diğer Olağan Gelir ve Karlar', classCode: '6' },
  { code: '653', title: 'Komisyon Giderleri (-)', classCode: '6' },
  { code: '654', title: 'Karşılık Giderleri (-)', classCode: '6' },
  { code: '655', title: 'Menkul Kıymet Satış Zararları (-)', classCode: '6' },
  { code: '656', title: 'Kambiyo Zararları (-)', classCode: '6' },
  { code: '657', title: 'Reeskont Faiz Giderleri (-)', classCode: '6' },
  { code: '658', title: 'Enflasyon Düzeltmesi Zararları(-)', classCode: '6' },
  { code: '659', title: 'Diğer Olağan Gider ve Zararlar (-)', classCode: '6' },
  { code: '660', title: 'Kısa Vadeli Borçlanma Giderleri (-)', classCode: '6' },
  { code: '661', title: 'Uzun Vadeli Borçlanma Giderleri (-)', classCode: '6' },
  { code: '671', title: 'Önceki Dönem Gelir ve Karları', classCode: '6' },
  { code: '679', title: 'Diğer Olağandışı Gelir ve Karlar', classCode: '6' },
  { code: '680', title: 'Çalışmayan Kısım Gider ve Zararları (-)', classCode: '6' },
  { code: '681', title: 'Önceki Dönem Gider ve Zararları (-)', classCode: '6' },
  { code: '689', title: 'Diğer Olağandışı Gider ve Zararlar (-)', classCode: '6' },
  { code: '690', title: 'Dönem Karı veya Zararı', classCode: '6' },
  { code: '691', title: 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', classCode: '6' },
  { code: '692', title: 'Dönem Net Karı veya Zararı', classCode: '6' },
  { code: '697', title: 'Yıllara Yaygın İnşaat Enflasyon Düzeltme', classCode: '6' },
  { code: '698', title: 'Enflasyon Düzeltme', classCode: '6' },
  { code: '700', title: 'Maliyet Muhasebesi Bağlantı Hesapları', classCode: '7' },
  { code: '701', title: 'Maliyet Muhasebesi Yansıtma Hesabı', classCode: '7' },
  { code: '710', title: 'Direkt İlk Madde ve Malzeme Giderleri', classCode: '7' },
  { code: '711', title: 'Direkt İlk Madde ve Malzeme Yansıtma Hesabı', classCode: '7' },
  { code: '712', title: 'Direkt İlk Madde ve Malzeme Fiyat Farkı', classCode: '7' },
  { code: '713', title: 'Direkt İlk Madde ve Malzeme Miktar Farkı', classCode: '7' },
  { code: '720', title: 'Direkt İşçilik Giderleri', classCode: '7' },
  { code: '721', title: 'Direkt İşçilik Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '722', title: 'Direkt İşçilik Ücret Farkları', classCode: '7' },
  { code: '723', title: 'Direkt İşçilik Süre (Zaman) Farkları', classCode: '7' },
  { code: '730', title: 'Genel Üretim Giderleri', classCode: '7' },
  { code: '731', title: 'Genel Üretim Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '732', title: 'Genel Üretim Giderleri Bütçe Farkları', classCode: '7' },
  { code: '733', title: 'Genel Üretim Giderleri Verimlilik Farkları', classCode: '7' },
  { code: '734', title: 'Genel Üretim Giderleri Kapasite Farkları', classCode: '7' },
  { code: '740', title: 'Hizmet Üretim Maliyeti', classCode: '7' },
  { code: '741', title: 'Hizmet Üretim Maliyeti Yansıtma Hesabı', classCode: '7' },
  { code: '742', title: 'Hizmet Üretim Maliyeti Fark Hesapları', classCode: '7' },
  { code: '750', title: 'Araştırma ve Geliştirme Giderleri', classCode: '7' },
  { code: '751', title: 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '752', title: 'Araştırma ve Geliştirme Gider Farkları', classCode: '7' },
  { code: '760', title: 'Pazarlama ,Satış ve Dağıtım Giderleri', classCode: '7' },
  { code: '761', title: 'Pazarlama ,Satış ve Dağıtım Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '762', title: 'Pazarlama ,Satış ve Dağıtım Giderleri Fark Hesabı', classCode: '7' },
  { code: '770', title: 'Genel Yönetim Giderleri', classCode: '7' },
  { code: '771', title: 'Genel Yönetim Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '772', title: 'Genel Yönetim Gider Farkları Hesabı', classCode: '7' },
  { code: '780', title: 'Finansman Giderleri', classCode: '7' },
  { code: '781', title: 'Finansman Giderleri Yansıtma Hesabı', classCode: '7' },
  { code: '782', title: 'Finansman Giderleri Fark Hesabı', classCode: '7' },
  { code: '790', title: 'İlk Madde ve Malzeme Giderleri', classCode: '7' },
  { code: '791', title: 'İşçi Ücret ve Giderleri', classCode: '7' },
  { code: '792', title: 'Memur Ücret ve Giderleri', classCode: '7' },
  { code: '793', title: 'Dışarıdan Sağlanan Fayda ve Hizmetler', classCode: '7' },
  { code: '794', title: 'Çeşitli Giderler', classCode: '7' },
  { code: '795', title: 'Vergi, Resim ve Harçlar', classCode: '7' },
  { code: '796', title: 'Amortismanlar ve Tükenme Payları', classCode: '7' },
  { code: '797', title: 'Finansman Giderleri', classCode: '7' },
  { code: '798', title: 'Gider Çeşitleri Yansıtma Hesabı', classCode: '7' },
  { code: '799', title: 'Üretim Maliyet Hesabı', classCode: '7' },
];
